#!/bin/bash
# Delete auto-generated Kconfig files in nuttx-apps so mkkconfig regenerates them
# Auto-generated Kconfig files contain absolute source paths
set -e

APPS_DIR="/home/polar/picocalc-term/nuttx-apps"

echo "Finding auto-generated Kconfig files with absolute paths..."
# These contain 'source "/...' with absolute paths - clear sign they're auto-generated
files=$(grep -rl 'source "/' "$APPS_DIR" --include="Kconfig" 2>/dev/null || true)

if [ -z "$files" ]; then
    echo "No auto-generated Kconfig files with absolute paths found."
    exit 0
fi

for f in $files; do
    echo "  Removing: $f"
    rm -f "$f"
done

echo "Done. Removed $(echo "$files" | wc -l) auto-generated Kconfig files."
echo "They will be regenerated by mkkconfig during the next build."
