#!/bin/bash
# tools/mkrootfs.sh — Generate ROMFS image from rootfs/ directory
#
# Usage: ./tools/mkrootfs.sh [output_dir]
#
# This script:
#   1. Copies rootfs/ template to build/rootfs/
#   2. Sets executable permissions on scripts
#   3. Generates a ROMFS image using genromfs
#   4. Converts the image to a C header for linking into firmware
#
# Requires: genromfs (apt install genromfs)

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
BUILD_DIR="${1:-$ROOT_DIR/build}"
ROOTFS_SRC="$ROOT_DIR/rootfs"
ROOTFS_DST="$BUILD_DIR/rootfs"
ROMFS_IMG="$BUILD_DIR/romfs.img"
ROMFS_HDR="$BUILD_DIR/romfs_img.h"

# Verify genromfs is installed
if ! command -v genromfs &> /dev/null; then
    echo "ERROR: genromfs not found. Install with: sudo apt install genromfs"
    exit 1
fi

# Verify rootfs source exists
if [ ! -d "$ROOTFS_SRC" ]; then
    echo "ERROR: rootfs/ directory not found at $ROOTFS_SRC"
    exit 1
fi

echo "==> Generating eUX ROMFS image"
echo "    Source:  $ROOTFS_SRC"
echo "    Build:   $BUILD_DIR"

# Clean and create build directory
rm -rf "$ROOTFS_DST"
mkdir -p "$ROOTFS_DST"
mkdir -p "$BUILD_DIR"

# Copy rootfs template
cp -r "$ROOTFS_SRC"/* "$ROOTFS_DST"/

# Set executable permissions on scripts
chmod +x "$ROOTFS_DST/etc/init.d/rcS" 2>/dev/null || true
find "$ROOTFS_DST/etc/sv" -name "run" -exec chmod +x {} \; 2>/dev/null || true

# Generate ROMFS image
genromfs -f "$ROMFS_IMG" -d "$ROOTFS_DST" -V "eUX"

ROMFS_SIZE=$(stat -c%s "$ROMFS_IMG" 2>/dev/null || stat -f%z "$ROMFS_IMG")
echo "    ROMFS:   $ROMFS_IMG ($ROMFS_SIZE bytes)"

# Convert to C header using xxd
xxd -i "$ROMFS_IMG" > "$ROMFS_HDR.tmp"

# Normalize the variable names (xxd uses the full path as name)
cat > "$ROMFS_HDR" << 'HEADER_START'
/****************************************************************************
 * build/romfs_img.h
 *
 * Auto-generated ROMFS image for eUX OS root filesystem.
 * Generated by tools/mkrootfs.sh — DO NOT EDIT.
 *
 ****************************************************************************/

#ifndef __BUILD_ROMFS_IMG_H
#define __BUILD_ROMFS_IMG_H

HEADER_START

# Extract the array data and size from xxd output, normalize names
sed -e 's/unsigned char .*/unsigned char romfs_img[] = {/' \
    -e 's/unsigned int .*/unsigned int romfs_img_len =/' \
    "$ROMFS_HDR.tmp" >> "$ROMFS_HDR"

echo "" >> "$ROMFS_HDR"
echo "#endif /* __BUILD_ROMFS_IMG_H */" >> "$ROMFS_HDR"

rm -f "$ROMFS_HDR.tmp"

echo "    Header:  $ROMFS_HDR"
echo "==> ROMFS generation complete"
